### ISSUE TITLE
Update on SpecFlow

### ISSUE THREAD

**Issue by seadoherty** [seadoherty/customerTestingCluster#5]
Wanted to give you an update:
Read the issues backward and started looking up the references before installing Specflow.
Getting hemmed up installing the extension on VS Studio (<--super odd because the step by step on the site isn't the same)
I'll figure out a workaround or alternative tool but it's driving me nuts because I'd prefer to use what seems to be the most used tool.

**Comment by damondouglas** [comment]
I'd say at a minimum the gherkin/cucumber at best is a good communication tool.  If it doesn't work out for you in terms of the tooling, I'd say just ditch getting the tooling to work.  Gherkin/cucumber was originally developed in the Java language so either use that language or just ditch getting the feature tests to work.
